// src/routes/cv/+page.svelte
<h1>CV</h1>
<div>
	<h3>Academic degrees</h3>
	<ul>
	<li>PhD in Computer Science </li>
	<li>M.Sc in Electronic Engineering</li>
	<li>B.Sc (Hons.) in Electrical & Electronic Engineering</li>
	</ul>
	
	<h3>Certificates</h3>
	<ul>
	<li>IBM Data Science Professional Certificate by IBM on Coursera</li>
	<li>Professional Certificate of "DeepLearning.AI TensorFlow Developer", by DeepLearning.AI
	    on Coursera</li>
	<li>Professional Certificate in "Unlocking Information Security" by Tel Aviv University, 
	    IsraelX & edX</li>
	</ul>
		
	<h3>Research specialism</h3>
	<ul>
	<li>Computer vision</li>
	<li>Machine learning</li>
	</ul>

	<h3>Skills & experience</h3>
	<ul>
	<li>Programming languages: Python, Java, JavaScript, C++</li>
	<li>Web frameworks: Flask, Django, ReactJS, Svelte, SvelteKit, Next.js, Vue</li>
	<li>Machine learning library: Tensorflow, scikit-learn, Weka</li>
	<li>Computer vision library: OpenCV, scikit-image</li>
	</ul>
</div>

// src/Components/CV.jsx
function CV() {
  return (
    <div>
	<h2>CV</h2>
	<h3>Academic degrees</h3>
	<ul>
	<li>PhD in Computer Science </li>
	<li>M.Sc in Electronic Engineering</li>
	<li>B.Sc (Hons.) in Electrical & Electronic Engineering</li>
	</ul>
	
	<h3>Certificates</h3>
	<ul>
	<li>IBM Data Science Professional Certificate by IBM on Coursera</li>
	<li>Professional Certificate of "DeepLearning.AI TensorFlow Developer", by DeepLearning.AI on Coursera</li>
	</ul>
		
	<h3>Research specialism</h3>
	<ul>
	<li>Computer vision</li>
	<li>Machine learning</li>
	</ul>

	<h3>Skills & experience</h3>
	<ul>
	<li>Programming languages: Python, Java, JavaScript, C#, C++</li>
	<li>Web frameworks: Flask, Django, Next.js, React.js, Svelte, Sveltekit, Vue.js</li>
	<li>Machine learning library: Tensorflow, scikit-learn</li>
	<li>Computer vision library: OpenCV, scikit-image</li>
	</ul>
	</div>
);
}
export default CV;
