// src/routes/photos/+page.svelte
<script>
let count = 1;

function select() {
   count +=1;
   if (count > 3) 
      {count = 1;}
}
</script>

<div class="photos">
   <h1>Photos</h1>
   <button on:click={select}> <b>Click to select next photo</b></button>
   <br />

   {#if count==1}
   <h4>Australian Catholic University, Strathfield Campus, NSW, Australia</h4>
   <img src="/acupy.jpg" alt="acu">
   {/if}

   {#if count==2}
   <h4>University of Technology Sydney, Building 5</h4>
   <img src="/uts-bldg5.jpg" alt="uts">
   {/if}

   {#if count==3}
   <h4>Homebush Public School, Homebush, NSW, Australia</h4>
   <img src="/hps.jpg" alt="hps">
   {/if}   
</div>

<style>
img {
   max-width: 100%;
   height: auto;
}
</style>

// src/Components/Photos.jsx
import utsbldg5 from './images/uts-bldg5r.jpg';
import hps from './images/hps1.jpg';
import acupy from './images/acupy.jpg';
import { useState } from 'react';

const images = [acupy, utsbldg5, hps] 
const desc = [
   'Australian Catholic University, Strathfield campus, Sydney, Australia',
   'UTS Haymarket Building 5, University of Technology Sydney, Australia',
   'Homebush Public School, Homebush, NSW, Australia'
]
const alt = [ 'acu', 'uts', 'hps' ]

export default function Photos() {
   const [count, setCount] = useState(0);
  
   function handleClick() {
      setCount((count + 1) % 3); 
   }	

   function acu() {
      setCount(0); 
   }
   
   function uts() {
      setCount(1); 
   }
   
   function hps() {
      setCount(2); 
   }
   
   return (
      <div>
      <h2>Photos</h2>
	  <p>Click Next photo button or select a photo with the name on the button</p>
      <button onClick={handleClick}>
      Next photo
      </button> |
	  <button onClick={acu}>
      Australian Catholic University
      </button> |
	  <button onClick={uts}>
      University of Technology Sydney
      </button> |
	  <button onClick={hps}>
      Homebush Public School
      </button>
	  
      <h4>{desc[count]}</h4>
      <img src={images[count]} alt={alt[count]} />
      <br />
      </div>
   );
}
