// src/routes/privacy/+page.svelte
<h1>Privacy policy</h1>
<h2>My contact</h2>
	<p>Email: mwong[at]mwongsite.com, replace [at] by @ </p>
	<p>If you contact the site author by email, your name, 
		email address and other information you provide to the 
		site author will be stored in the email account of the site 
		author.</p>
		
<h2>Cookies</h2>
	<p>This website might use cookies to improve your experience of 
	using the site. If you continue to use this site, it will be 
	assumed that you agree to the use of cookies.</p>

	<p>The above privacy policy can be changed at any time by 
	the site author without giving notice.</p>

// src/Components/Privacy.jsx
function Privacy() {
  return (
    <div>	
	<h2>Privacy Policy</h2>
	<h3>Who we are</h3>
	<p>Our website address is: https://mwongau.github.io</p>
	<p>This is the personal site of M. Wong.</p>
	
	<h3>Contact</h3>
	<p>GitHub: https://github.com/mwongau </p>
	<p>Email: mwong[at]mwongsite.com, replace [at] by @ </p>
	<p>If you contact the site author by email, your name, 
		email address and other information you provide to the 
		site author will be stored in the email account of the site 
		author.</p>
		
	<h3>Cookies</h3>
	<p>This website uses cookies to improve your experience of 
	using the site. If you continue to use this site, it will be 
	assumed that you agree to the use of cookies.</p>

	<p>The above privacy policy can be changed at any time by 
	the site author without giving notice.</p>	
	</div>
);
}
export default Privacy;
